### ISSUE TITLE
Writing an LLVM Pass

### ISSUE THREAD

**Issue by chouqin** [zjuacompiler/llvm#8]
## 任务

照着[Writing an LLVM Pass](http://llvm.org/docs/WritingAnLLVMPass.html)这个文档走一遍，把里面的内容弄明白。
## 目标

希望做完之后能够达到以下几个目的：
1. 知道LLVM的Pass能做哪些事情，我们的这个Project能利用到哪些信息
2. 在`include/llvm/IR/LegacyPassManagers.h`的注释中提到PassManager的作用：

``` cpp
// The Pass Manager Infrastructure manages passes. It's responsibilities are:
//
//   o Manage optimization pass execution order
//   o Make required Analysis information available before pass P is run
//   o Release memory occupied by dead passes
//   o If Analysis information is dirtied by a pass then regenerate Analysis
//     information before it is consumed by another pass.
```

这里面的Analysis information到底有什么用，在Pass P中是如何使用这些Analysis Information的？
### 两个接口类：

PMDataManager, PMTopLevelManager
### 层次：

因为有两个TopLevelManager，所以有两种路径，分别从PassManager和FunctionPassManager开始。
#### 从PassManager开始：
1. PassManager, PassManagerImpl: 管理Passes，其中PassManagerImpl是一种PMTopLevelManager，可以对外提供接口
2. MPPassManager，是Pass的一种，管理ModulePasses
3. FPPassManager，是ModulePass的一种，管理FunctionPasses
4. BBPassManagers，是FuctionPass的一种，管理BasicBlockPasses
#### 从FunctionPassManager开始：
1. FunctionPassManager, PassManagerImpl: 管理FPPassManager，其中FunctionPassManagerImpl是一种PMTopLevelManager，可以对JIT提供接口
2. FPPassManager管理FunctionPasses
3. BBPassManagers，是FuctionPass的一种，管理BasicBlockPasses

**Comment by chouqin** [comment]
如果有什么问题直接说，我们一起来解决

**Comment by KarayLee** [comment]
Ok,
